### PR TITLE
maxSequences of instance numbers & DefaultHander for response body

### PR DESCRIPTION
**Pull request by mossuchida**
Please find the update code for maxSequences.  With this code, user is able to set their desired maxSequences number & .  Default is still 16.

Also, requesting to add default handler to allow user to retrieve response body as is.

### CODE REVIEW

**Comment by rvansa** [comment]
Hi, I've updated the PR to fix few things:
* If you create many commits, stash them into logical units. Do not use merge commits; we keep linear history for clarity, so rebase your stashed changes onto master.
* Do not address completely unrelated issues in single PR. I've removed the `DefaultHandler` from this PR completely; I don't understand what this should be used for (you haven't replied on my questions on Zulip) and there's no accompanying example or test. Let's discuss this on Zulip.
* There should be only one `.gitignore` file in the repo (that file can include files in subdirectories). I am not sure what files were you trying to exclude. I've removed those.
* Minor fixes such as forgotten logging or missing `maxRequests` in the parser.

You don't have to close and reopen different PR when you want to change anything - just force push your branch.

**Comment by rvansa** [comment]
Integrated, thanks.

**Comment by mossuchida** [comment]
Thanks! All performance team that I have known in IBM don't code like developer, I got lazy. I am glad that I can work with you to keep up good code quality of this project! - I was not sure about DefaultHander - If I should include or not. Also, maxRequest also. I will do better next time :D

**Comment by rvansa** [comment]
I've looked into your use of the `default` handler in other benchmark file and it seems you're using it like
```yaml
            handler:
                body:
                - default:
                    processor:
                      simple:
                        toVar: flights
                        format: STRING
```
while you could just do
```yaml
              handler:
                body:
                - simple:
                     toVar: flights
```
I guess it is because in the past the `simple` recorder was not defragmenting automatically. You're safe now, though.

**Pull request merged**
