### PR TITLE
Replace HyperfoilChannelLookup

### PR DESCRIPTION
**Pull request by jabolina**
For more context: https://github.com/Hyperfoil/Hyperfoil/pull/349#issuecomment-2222299106

The idea is to have an XML file for the controller and another for the agents. This change should be equivalent to utilizing the `HyperfoilChannelLookup` unless people customize the `jgroups-tcp.xml`  file for the agents.

### CODE REVIEW

**Review by franz1981 — APPROVED** [review]
I'm not super familiar with that code paths @jabolina 
IDK if we have decent coverage there, but the change per se looks fine

**Comment by franz1981** [comment]
if @lampajr is fine, let's go and merge it!

**Comment by lampajr** [comment]
>I'm not super familiar with that code paths @jabolina

yeah me too, but it looks safe to me!

**Comment by jabolina** [comment]
Thanks, @lampajr and @franz1981! When @wburns is back, I'll ask for an additional review.

**Pull request merged**
