### PR TITLE
Enforce java codestyle

### PR DESCRIPTION
**Pull request by lampajr**
## Changes proposed

Automate formatting

## Check List (check all the applicable boxes) 

- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

> Note that the documentation is located at [github.com/Hyperfoil/hyperfoil.github.io](https://github.com/Hyperfoil/hyperfoil.github.io/) 

<details>
<summary>
How to backport a pull request to the current <em>stable</em> branch?
</summary>

In order to automatically create a **backporting pull request** please add `backport` label to the current pull request.

Then, as soon as the pull request is merged into the `master` branch, the process will try to automatically open a backporting pull request against the _stable_ branch. If something goes wrong, a comment will be added in the original pull request such that all people involved get notified.

> The `backport` label can be also added after the pull  request has been merged.

> If the process fails due to temporary problems, such as connectivity problems, consider removing and re-adding the `backport` label.
</details>

### CODE REVIEW

**Comment by lampajr** [comment]
Hi @franz1981, this is just a proposal to bootstrap a conversation on this topic.

I think that setting up an automation for the code formatting is really good to have, on the other hand I see that there will be many changes, thus I am not completely sure whether this is going to be a good change or not (at least for Hyperfoil).

**Review by franz1981 — CHANGES_REQUESTED** [review]
Please check what quarkus does: IIRC they format automatically the code, the same

**Comment by franz1981** [comment]
Fine to me, well done!

**Review by franz1981 — APPROVED** [review]

**Review by franz1981 — APPROVED** [review]
LGTM!

**Pull request merged**
