### PR TITLE
Setup Hyperfoil website documentation

### PR DESCRIPTION
**Pull request by lampajr**
## Changes proposed

Move Hyperfoil documentation in this repository to make our life easier.
- [x] Moved from https://github.com/Hyperfoil/Hyperfoil.github.io to this repo.
- [x] Huge refactoring to make use of [hugo](https://gohugo.io/) with [docsy](https://www.docsy.dev/) theme (following the Horreum documentation stack).
- [x] Update RELEASE.md documentation

## Check List (check all the applicable boxes) 

- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

> Note that the documentation is located at [github.com/Hyperfoil/hyperfoil.github.io](https://github.com/Hyperfoil/hyperfoil.github.io/) 

<details>
<summary>
How to backport a pull request to the current <em>stable</em> branch?
</summary>

In order to automatically create a **backporting pull request** please add `backport` label to the current pull request.

Then, as soon as the pull request is merged into the `master` branch, the process will try to automatically open a backporting pull request against the _stable_ branch. If something goes wrong, a comment will be added in the original pull request such that all people involved get notified.

> The `backport` label can be also added after the pull  request has been merged.

> If the process fails due to temporary problems, such as connectivity problems, consider removing and re-adding the `backport` label.
</details>

### CODE REVIEW

**Comment by lampajr** [comment]
You can checkout a hosted demo example of this new website: https://lampajr.github.io/hyperfoil-website-demo

> [!NOTE]
> The deployment configuration/workflow can be found at https://github.com/lampajr/hyperfoil-website-demo/blob/main/.github/workflows/deploy-github-pages.yaml

**Review by franz1981 — COMMENTED** [review]
wow, well done! I have to give a shot to it again, but looks fine to me!

**Comment by lampajr** [comment]
Just fixed a couple of issues I found on the generated markdowns from the Javadoc.
Moreover I was able toreuse the logo we are currently using for the doc:
image

**Comment by franz1981** [comment]
I'm fine with the changes, thanks @lampajr 

just a personal note

image


vs

image


I still have to decide if I prefer the former or the latter rep, with many rows and columns probably the old one!
But I believe is something which can be changed later on based on user feedbacks, not mine!

**Review by franz1981 — APPROVED** [review]
LGTM

**Comment by lampajr** [comment]
>I still have to decide if I prefer the former or the latter rep, with many rows and columns probably the old one!
But I believe is something which can be changed later on based on user feedbacks, not mine!

yeah that's a good point, the tabular approach might be easier to understand when there are many rows as you pointed out. At the moment I used the default view coming from `docsy` theme but I think we can customize it later if we decide to do that

**Comment by rh-appservices-perf** [comment]
The backport to `0.26.x` failed. Check the latest run for more details.

**Pull request merged**
