### PR TITLE
Update to Infinispan 14.0.9.Final

### PR DESCRIPTION
**Pull request by alanfx**
Resolves https://github.com/Hyperfoil/Hyperfoil/issues/255

### CODE REVIEW

**Review by franz1981 — APPROVED** [review]
Thanks!

**Review by franz1981 — APPROVED** [review]
Thanks!

**Comment by jesperpedersen** [comment]
@alanfx @franz1981 Could you look at this NPEs ? Thanks !

**Comment by alanfx** [comment]
Hey @jesperpedersen trying to look at this now, but I am hitting two issues. If I try to run `mvn package`, I get the following test case failure:

`[INFO] Running io.hyperfoil.http.CertificatesTest
[ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.621 s <<< FAILURE! - in io.hyperfoil.http.CertificatesTest
[ERROR] io.hyperfoil.http.CertificatesTest.testClientBadJks  Time elapsed: 0.063 s  <<< FAILURE!
java.lang.AssertionError: Was expecting a failure instead of of success
	at io.vertx.ext.unit.impl.TestContextImpl.reportAssertionError(TestContextImpl.java:362)
	at io.vertx.ext.unit.impl.TestContextImpl.lambda$asyncAssertFailure$6(TestContextImpl.java:345)
	at io.hyperfoil.http.connection.HttpClientPoolImpl.lambda$start$4(HttpClientPoolImpl.java:310)
	at io.hyperfoil.http.connection.SharedConnectionPool.handleNewConnection(SharedConnectionPool.java:315)
	at io.hyperfoil.http.connection.Http1xConnection.checkActivated(Http1xConnection.java:75)
	at io.hyperfoil.http.connection.Http1xConnection.handlerAdded(Http1xConnection.java:62)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:223)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:195)
	at io.hyperfoil.http.connection.HttpChannelInitializer.initHttp1xConnection(HttpChannelInitializer.java:105)
	at io.hyperfoil.http.connection.HttpChannelInitializer$1.configurePipeline(HttpChannelInitializer.java:40)
	at io.netty.handler.ssl.ApplicationProtocolNegotiationHandler.userEventTriggered(ApplicationProtocolNegotiationHandler.java:139)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:400)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:376)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:368)
	at io.netty.handler.ssl.SslHandler.setHandshakeSuccess(SslHandler.java:1848)
	at io.netty.handler.ssl.SslHandler.wrapNonAppData(SslHandler.java:952)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1419)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1257)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1297)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:544)
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:387)
	at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:213)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:291)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)`

And if I run `mvn -DskipTests=true package`, I get this build failure:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (default) on project hyperfoil-hotrod: An Ant BuildException has occured: src '/Users/afield/Development/projects/Hyperfoil/hotrod/target/hyperfoil-hotrod-shaded.jar' doesn't exist.
[ERROR] around Ant part ...<unzip src="/Users/afield/Development/projects/Hyperfoil/hotrod/target/hyperfoil-hotrod-shaded.jar" dest="/Users/afield/Development/projects/Hyperfoil/hotrod/target/shaded"/>... @ 4:177 in /Users/afield/Development/projects/Hyperfoil/hotrod/target/antrun/build-main.xml`

So, any ideas welcomed, and I'll keep digging!

**Comment by alanfx** [comment]
I got past the errors by using a Linux container for building vs native MacOS. The tests fail with an error about the KQueue native transport for some reason. I was not able to reproduce the NPE, so I am force pushing a couple of minor changes to see if CI runs into the same issues.

**Comment by jesperpedersen** [comment]
@alanfx @franz1981 There is a test failure here

**Comment by jesperpedersen** [comment]
Please, reopen once fixed

**Comment by alanfx** [comment]
Yeah, I haven't been able to figure out how to get past the `java.lang.IllegalStateException: incompatible event loop type: io.netty.channel.kqueue.KQueueEventLoop` issue, and I don't have a lot of time to debug it ATM.

**Pull request closed without merging**
