### PR TITLE
Export standard deviation for response time

### PR DESCRIPTION
**Pull request by jabolina**
## Changes proposed

Export the standard deviation for response time.
I am afraid this could break compatibility somehow, especially on the CSV bits. But this would be a useful information to have on the reports.

## Check List (check all the applicable boxes) 

- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by franz1981 — APPROVED** [review]
LGTM!

**Comment by jabolina** [comment]
Thanks! Updated the CLI:

```
PHASE          METRIC   THROUGHPUT   REQUESTS  MEAN       STD_DEV    p50        p90        p99      p99.9    p99.99   TIMEOUTS  ERRORS  BLOCKED
writes10to100  putData  54.18 req/s      3251  634.21 μs  249.65 μs  704.51 μs  864.26 μs  1.07 ms  1.29 ms  6.19 ms         0       0     0 ns
```

Going to open a PR for the report in just a moment.

**Comment by jabolina** [comment]
I see. I'll open the PR to https://github.com/Hyperfoil/report/ to include the new column. With the generated HTML, I'll open a PR to https://github.com/Hyperfoil/hyperfoil.github.io/. Once the second one is merged, I'll update the URL to the new report template in this PR.

**Comment by jabolina** [comment]
Created the PRs to include the column in the report. I'll update this PR after we have the URL to the new report template.

**Comment by lampajr** [comment]
> Created the PRs to include the column in the report. I'll update this PR after we have the URL to the new report template.

Thanks again @jabolina , PRs already merged and the new template is already available at https://hyperfoil.io/report-template-v3.1.html

**Comment by jabolina** [comment]
Thanks! Just updated it to utilize the new report template.

**Review by lampajr — APPROVED** [review]
Looks awesome!

**Comment by jabolina** [comment]
Thanks for the help <3

**Pull request merged**
